# Generated by Django 4.0.6 on 2022-07-18 14:36

import app.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0010_usermodel_please_upload_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='allDevices',
            fields=[
                ('allDevices_id_id', models.CharField(default=0, max_length=40, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_installed', models.DateField(default=app.utils.dt)),
                ('allDevices_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.alldevices')),
            ],
        ),
        migrations.CreateModel(
            name='field',
            fields=[
                ('field_name', models.CharField(max_length=15)),
                ('field_id', models.CharField(default=app.utils.create_new_ref_number, max_length=10, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='place',
            fields=[
                ('p_id', models.CharField(default=app.utils.create_new_ref_number, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('p_type', models.CharField(max_length=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='subuseraccess',
            fields=[
                ('email', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.DeleteModel(
            name='UserModel',
        ),
        migrations.CreateModel(
            name='Device_status',
            fields=[
                ('allDevices_id_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.alldevices')),
                ('pin2Status', models.IntegerField(blank=True, default=0, null=True)),
                ('pin1Status', models.IntegerField(blank=True, default=0, null=True)),
                ('pin3Status', models.IntegerField(blank=True, default=0, null=True)),
                ('pin4Status', models.IntegerField(blank=True, default=0, null=True)),
                ('pin5Status', models.IntegerField(blank=True, default=0, null=True)),
                ('pin6Status', models.IntegerField(blank=True, default=0, null=True)),
                ('pin7Status', models.IntegerField(blank=True, default=0, null=True)),
                ('sensor1', models.FloatField(blank=True, default=0.0, max_length=50)),
                ('sensor2', models.FloatField(blank=True, default=0.0, max_length=50)),
                ('sensor3', models.FloatField(blank=True, default=0.0, max_length=50)),
                ('sensor4', models.FloatField(blank=True, default=0.0, max_length=50)),
                ('sensor5', models.FloatField(blank=True, default=0.0, max_length=50)),
                ('sensor6', models.FloatField(blank=True, default=0.0, max_length=50)),
                ('sensor7', models.FloatField(blank=True, default=0.0, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pin_name',
            fields=[
                ('allDevices_id_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.alldevices')),
                ('pin1Name', models.CharField(blank=True, max_length=20, null=True)),
                ('pin2Name', models.CharField(blank=True, max_length=20, null=True)),
                ('pin3Name', models.CharField(blank=True, max_length=20, null=True)),
                ('pin4Name', models.CharField(blank=True, max_length=20, null=True)),
                ('pin5Name', models.CharField(blank=True, max_length=20, null=True)),
                ('pin6Name', models.CharField(blank=True, max_length=20, null=True)),
                ('pin7Name', models.CharField(blank=True, max_length=20, null=True)),
                ('pin8Name', models.CharField(blank=True, max_length=20, null=True)),
                ('pin9Name', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='field',
            name='place_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.place'),
        ),
        migrations.AddField(
            model_name='field',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='device',
            name='field_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.field'),
        ),
        migrations.AddField(
            model_name='device',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='subuserplace',
            fields=[
                ('owner_name', models.CharField(blank=True, max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.subuseraccess', unique=True)),
                ('place_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.place', unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
