# Generated by Django 4.0.6 on 2022-07-21 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rename_alldevices_id_id_alldevices_alldevices_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device_status',
            old_name='allDevices_id_id',
            new_name='allDevices_id',
        ),
        migrations.RenameField(
            model_name='pin_name',
            old_name='allDevices_id_id',
            new_name='allDevices_id',
        ),
    ]
