# Generated by Django 4.0.6 on 2022-07-22 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_remove_tempuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
