# Generated by Django 4.0.6 on 2022-07-28 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_rename_p_id_place_place_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tempuser',
            old_name='d_id',
            new_name='allDevices_id',
        ),
    ]
