# Generated by Django 4.0.6 on 2022-08-01 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='f_name',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='p_type',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
