# Generated by Django 4.0.6 on 2022-08-02 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='d_id',
        ),
        migrations.RemoveField(
            model_name='device',
            name='f_id',
        ),
        migrations.RemoveField(
            model_name='device',
            name='user',
        ),
        migrations.RemoveField(
            model_name='devicestatus',
            name='d_id',
        ),
        migrations.RemoveField(
            model_name='field',
            name='p_id',
        ),
        migrations.RemoveField(
            model_name='field',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tempuser',
            name='d_id',
        ),
        migrations.RemoveField(
            model_name='tempuser',
            name='device_id',
        ),
        migrations.RemoveField(
            model_name='tempuser',
            name='f_id',
        ),
        migrations.AddField(
            model_name='subuserplace',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='place',
            name='p_type',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='subuserplace',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.subuseraccess'),
        ),
        migrations.AlterField(
            model_name='tempuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='tempuser',
            name='mobile',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='tempuser',
            name='owner_name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='tempuser',
            name='timing',
            field=models.CharField(default='00:00', max_length=200),
        ),
        migrations.DeleteModel(
            name='allDevices',
        ),
        migrations.DeleteModel(
            name='device',
        ),
        migrations.DeleteModel(
            name='deviceStatus',
        ),
        migrations.DeleteModel(
            name='field',
        ),
    ]
