# Generated by Django 4.0.6 on 2022-07-29 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_device_status_pin_name_remove_deviceipaddress_d_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alldevices',
            old_name='allDevices_id',
            new_name='d_id',
        ),
        migrations.RenameField(
            model_name='device',
            old_name='allDevices_id',
            new_name='d_id',
        ),
        migrations.RenameField(
            model_name='device',
            old_name='field_id',
            new_name='f_id',
        ),
        migrations.RenameField(
            model_name='device',
            old_name='user_id',
            new_name='user',
        ),
    ]
