# Generated by Django 4.0.6 on 2022-08-01 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_field_f_name_alter_place_p_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subuserplace',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='subuserplace',
            name='owner_name',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
