# Generated by Django 4.0.6 on 2022-08-01 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_subuserplace_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='tempuser',
            name='mobile',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='tempuser',
            name='owner_name',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
