# Generated by Django 4.0.6 on 2022-07-29 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_alldevices_id_alldevices_d_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Device_status',
            new_name='deviceStatus',
        ),
        migrations.RenameModel(
            old_name='Pin_name',
            new_name='pinName',
        ),
        migrations.RenameField(
            model_name='devicestatus',
            old_name='allDevices_id',
            new_name='d_id',
        ),
        migrations.RenameField(
            model_name='pinname',
            old_name='allDevices_id',
            new_name='d_id',
        ),
        migrations.RenameField(
            model_name='subuserplace',
            old_name='place_id',
            new_name='p_id',
        ),
        migrations.RenameField(
            model_name='tempuser',
            old_name='allDevices_id',
            new_name='d_id',
        ),
        migrations.RenameField(
            model_name='tempuser',
            old_name='field_id',
            new_name='f_id',
        ),
        migrations.RenameField(
            model_name='tempuser',
            old_name='place_id',
            new_name='p_id',
        ),
    ]
