# Generated by Django 4.0.6 on 2022-07-31 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_subuseraccess_emailtest_subuseraccess_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subuseraccess',
            old_name='user',
            new_name='emailtest',
        ),
    ]
